//! TOML configuration.
//!
//! Secrets (argon2 hash, TOTP secret, JWT key) are read from this file or the
//! environment, never compiled into the binary. Sections are filled in as the
//! build progresses; everything has a working default except the auth material,
//! which `facet setup` generates.

use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct Config {
    #[serde(default)]
    pub server: Server,
    #[serde(default)]
    pub shell: Shell,
    #[serde(default)]
    pub tls: Tls,
    #[serde(default)]
    pub terminals: Terminals,
    /// Absent until `facet setup` has run. Without it the server refuses to
    /// start: there is no anonymous mode, by design.
    pub auth: Option<Auth>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct Terminals {
    /// Cap on concurrent shells, so a runaway client cannot fork-bomb by
    /// opening tabs.
    pub max: usize,
    /// Bytes of output kept per terminal and replayed on reconnect. This is the
    /// memory cost of the "close your laptop and come back" feature: worst case
    /// `max * scrollback_bytes`.
    pub scrollback_bytes: usize,
    /// How long a terminal survives with nothing attached before it is reaped.
    /// Set to 0 to keep detached shells forever.
    pub detached_timeout_minutes: u64,
}

impl Default for Terminals {
    fn default() -> Self {
        Self {
            max: 10,
            scrollback_bytes: 256 * 1024,
            detached_timeout_minutes: 60,
        }
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct Server {
    /// Loopback by default. Exposing this to a LAN or the internet is an
    /// explicit, documented choice. See the README's exposure section.
    pub bind: IpAddr,
    pub port: u16,
    /// Extra origins accepted on the WebSocket upgrade, beyond "same host as
    /// the request". Needed only when a proxy rewrites `Host` such that it no
    /// longer matches the browser's `Origin`; a plain Tailscale or Cloudflare
    /// Tunnel setup does not need this.
    #[serde(default)]
    pub allowed_origins: Vec<String>,
    /// Where to append the audit log. `None` logs to stdout only.
    #[serde(default)]
    pub audit_log: Option<PathBuf>,
}

impl Default for Server {
    fn default() -> Self {
        Self {
            bind: IpAddr::V4(Ipv4Addr::LOCALHOST),
            port: 7443,
            allowed_origins: Vec::new(),
            audit_log: None,
        }
    }
}

impl Server {
    pub fn addr(&self) -> SocketAddr {
        SocketAddr::new(self.bind, self.port)
    }

    /// True when we are only reachable from this machine.
    pub fn is_loopback(&self) -> bool {
        self.bind.is_loopback()
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct Shell {
    /// Program to exec. Defaults are platform-specific; see [`Shell::default`].
    pub program: String,
    pub args: Vec<String>,
    /// Working directory for the shell. `None` means the user's home directory.
    pub cwd: Option<PathBuf>,
    /// Extra environment variables handed to the child.
    #[serde(default)]
    pub env: Vec<(String, String)>,
}

impl Default for Shell {
    #[cfg(windows)]
    fn default() -> Self {
        // Per the build brief: land in WSL bash by default on Windows.
        // `~` starts in the Linux home dir; `-l` gives a login shell so the
        // user's dotfiles run.
        Self {
            program: "wsl.exe".into(),
            args: ["~", "-e", "bash", "-l"]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            cwd: None,
            env: Vec::new(),
        }
    }

    #[cfg(not(windows))]
    fn default() -> Self {
        let program = std::env::var("SHELL").unwrap_or_else(|_| "/bin/bash".into());
        Self {
            program,
            args: vec!["-l".into()],
            cwd: None,
            env: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct Tls {
    /// On by default. Turning it off is only tolerated on loopback; see
    /// [`Config::validate`].
    pub enabled: bool,
    pub cert: PathBuf,
    pub key: PathBuf,
}

impl Default for Tls {
    fn default() -> Self {
        Self {
            enabled: true,
            cert: PathBuf::from("certs/cert.pem"),
            key: PathBuf::from("certs/key.pem"),
        }
    }
}

/// Credentials. Every field here is a secret and every one is generated by
/// `facet setup`. Nothing is compiled into the binary.
///
/// Each may be overridden by an environment variable, so the file can stay out
/// of your dotfiles repo entirely:
/// `FACET_PASSWORD_HASH`, `FACET_TOTP_SECRET`, `FACET_JWT_SECRET`.
#[derive(Clone, Deserialize, Serialize)]
pub struct Auth {
    /// PHC-format argon2id string. Contains its own salt and parameters.
    #[serde(default)]
    pub password_hash: String,
    /// Base32, as TOTP apps expect.
    #[serde(default)]
    pub totp_secret: String,
    /// Base64. Signs session JWTs; rotating it invalidates every session.
    #[serde(default)]
    pub jwt_secret: String,
    /// How long a login lasts before re-authentication is required.
    #[serde(default = "default_session_ttl")]
    pub session_ttl_minutes: u64,
    /// Consecutive failures before the account is locked out.
    #[serde(default = "default_max_failures")]
    pub max_failed_attempts: u32,
    /// How long a lockout lasts.
    #[serde(default = "default_lockout")]
    pub lockout_minutes: u64,
}

fn default_session_ttl() -> u64 {
    12 * 60
}
fn default_max_failures() -> u32 {
    5
}
fn default_lockout() -> u64 {
    15
}

/// Redacted: this struct is full of secrets and it would otherwise land in the
/// logs the first time someone debug-prints the config.
impl std::fmt::Debug for Auth {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Auth")
            .field("password_hash", &"<redacted>")
            .field("totp_secret", &"<redacted>")
            .field("jwt_secret", &"<redacted>")
            .field("session_ttl_minutes", &self.session_ttl_minutes)
            .field("max_failed_attempts", &self.max_failed_attempts)
            .field("lockout_minutes", &self.lockout_minutes)
            .finish()
    }
}

impl Auth {
    /// Let the environment win over the file, so secrets can live in a keychain
    /// or a systemd `EnvironmentFile` instead of on disk.
    fn apply_env(&mut self) {
        if let Ok(v) = std::env::var("FACET_PASSWORD_HASH") {
            self.password_hash = v;
        }
        if let Ok(v) = std::env::var("FACET_TOTP_SECRET") {
            self.totp_secret = v;
        }
        if let Ok(v) = std::env::var("FACET_JWT_SECRET") {
            self.jwt_secret = v;
        }
    }

    fn validate(&self) -> Result<()> {
        for (name, value) in [
            ("password_hash", &self.password_hash),
            ("totp_secret", &self.totp_secret),
            ("jwt_secret", &self.jwt_secret),
        ] {
            if value.trim().is_empty() {
                return Err(Error::Config(format!(
                    "auth.{name} is empty. Run `facet setup` to generate credentials"
                )));
            }
        }
        Ok(())
    }
}

impl Config {
    /// Read, overlay the environment, then refuse anything unsafe.
    pub fn load(path: &Path) -> Result<Self> {
        let raw = std::fs::read_to_string(path)
            .map_err(|e| Error::Config(format!("could not read {}: {e}", path.display())))?;

        let mut config: Self = toml::from_str(&raw)
            .map_err(|e| Error::Config(format!("could not parse {}: {e}", path.display())))?;

        if let Some(auth) = config.auth.as_mut() {
            auth.apply_env();
        }
        config.validate()?;
        Ok(config)
    }

    /// The safety interlocks. These are checked once, at startup, so that an
    /// unsafe deployment fails to boot rather than quietly serving a shell to
    /// the internet.
    pub fn validate(&self) -> Result<()> {
        // 1. No credentials, no server. There is no anonymous mode to fall
        //    back to, and no flag that creates one.
        let auth = self.auth.as_ref().ok_or_else(|| {
            Error::Config(
                "no [auth] section. Run `facet setup` first. facet will not serve a shell \
                 without credentials."
                    .into(),
            )
        })?;
        auth.validate()?;

        // 2. Plaintext HTTP is tolerable on loopback (you are already inside
        //    the trust boundary, and tunnels terminate TLS themselves). Off
        //    loopback it would put a session cookie and every keystroke on the
        //    wire in the clear, so we refuse.
        if !self.tls.enabled && !self.server.is_loopback() {
            return Err(Error::Config(format!(
                "tls.enabled = false with bind = {}: refusing to serve a shell unencrypted \
                 on a non-loopback address. Either enable TLS or bind 127.0.0.1 and put a \
                 tunnel in front (see the README).",
                self.server.bind
            )));
        }

        Ok(())
    }
}
